site_name: Das interaktive Musikbuch
site_description: Ein Online-Musikbuch mit interaktiven Beispielen
site_author: Herr Piesik

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Start: index.md
  - 1 Schwingung:
      - 1.1 Alles beginnt mit Bewegung: 01.01.md
      - 1.2 Was ist Schwingung?: 01.02.md
      - '1.3 Schall: Wenn Schwingung hörbar wird': 01.03.md
      - '1.4 Tonhöhe: Schnell oder langsam?': 01.04.md
      - 1.5 Warum ein Ton nie allein schwingt – die Obertöne: 01.05.md
      - 1.6 Warum Dur so vertraut klingt: 01.06.md
      - 1.7 Resonanz – wenn Schwingung stärker wird: 01.07.md
      - 1.8 Klangfarbe – warum Instrumente unterschiedlich klingen: 01.08.md
      - 1.9 Musik – geordnete Schwingung: 01.09.md
  - 02 Töne:
      - Eine Auswahl von Tönen: 02_obertöne.md
      - Aufgaben: 02_aufgaben.md
      - Experimente: 02_experimente.md
      - Merkkarten: 02_merkkarten.md

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - fenced_code


extra_javascript:
  - https://unpkg.com/@strudel/repl@latest
  - javascripts/strudel-controls.js
  - javascripts/strudel-hide-until-markers.js
  #- https://unpkg.com/abcjs@6.2.3/dist/abcjs-basic-min.js
  - https://cdn.jsdelivr.net/npm/abcjs@6.2.3/dist/abcjs-min.js
  - javascripts/abc-render.js

extra_css:
  - styles/strudel.css
  - styles/abc.css

