site_name: Interaktive Musiktheorie mit Strudel
site_description: Ein Online-Buch mit interaktiven Musikbeispielen
site_author: Herr Piesik

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Start: index.md
  - 01 Schwingungen:
      - Was ist Schwingung?: 01_schwingung.md
      - Aufträge: 01_aufträge.md
      - Experimente: 01_experiemnte.md
      - Merkkarten: 01_merkkarten.md
  - 01:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 02:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 03:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 04:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 05:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 06:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 07:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 08:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 09:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 10:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 11:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md
  - 12:
      - Klang & Ton: grundlagen.md
      - Rhythmus: rhythmus.md

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - https://unpkg.com/@strudel/repl@latest
  - javascripts/strudel-controls.js
  - javascripts/strudel-hide-until-markers.js

extra_css:
  - styles/strudel.css

