site_name: Interaktive Musiktheorie mit Strudel
site_description: Ein Online-Buch mit interaktiven Musikbeispielen
site_author: Herr Piesik

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Start: index.md
  - 01 Schwingung:
      - Alle beginnt mit Bewegung: 01.01.md
      - Was ist Schwingung?: 01.02.md
      - 'Schall: Wenn Schwingung hörbar wird': 01.03.md
      - 'Tonhöhe: Schnell oder langsam?': 01.04.md
      - Warum ein Ton nie allein schwingt – die Obertöne: 01.05.md
      - Warum Dur so vertraut klingt: 01.06.md
      - Resonanz – wenn Schwingung stärker wird: 01.07.md
      - Klangfarbe – warum Instrumente unterschiedlich klingen: 01.08.md
      - Musik – geordnete Schwingung: 01.09.md
  - 02 Rhytmus:
      - Eine Schwingung kommt selten allein: 02_obertöne.md
      - Aufgaben: 02_aufgaben.md
      - Experimente: 02_experimente.md
      - Merkkarten: 02_merkkarten.md

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - https://unpkg.com/@strudel/repl@latest
  - javascripts/strudel-controls.js
  - javascripts/strudel-hide-until-markers.js

extra_css:
  - styles/strudel.css

